version: '3.4'

services:
  accountdb:
    image: mongo

  projectdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  project.api:
    image: ${DOCKER_REGISTRY-}projectapi
    build:
      context: .
      dockerfile: Services/Project/Project.API/Dockerfile

  report.api:
    image: ${DOCKER_REGISTRY-}reportapi
    build:
      context: .
      dockerfile: Services/Report/Report.API/Dockerfile

  project.grpc:
    image: ${DOCKER_REGISTRY-}projectgrpc
    build:
      context: .
      dockerfile: Services/Project/Project.Grpc/Dockerfile

volumes:
  mongo_data:


