version: '3.4'

services:
  accountdb:
    container_name: accountdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  projectdb:
    container_name: projectdb
    environment:
      SA_PASSWORD: "ahihi214"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://accountdb:27017"
    depends_on:
      - accountdb
    ports:
      - "8000:80"

  project.api:
    container_name: project.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ProjectConnectionString=Server=projectdb;Database=ProjectDb;User Id=sa;Password=ahihi214;TrustServerCertificate=true"
    depends_on:
      - projectdb
    ports:
      - "8001:80"


  report.api:
    container_name: report.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ReportConnectionString=Server=projectdb;Database=ProjectDb;User Id=sa;Password=ahihi214;TrustServerCertificate=true"
      - "GrpcSettings:ProjectUrl=http://project.grpc"
    depends_on:
      - projectdb
    ports:
      - "8002:80"


  project.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:ProjectConnectionString=Server=projectdb;Database=ProjectDb;User Id=sa;Password=ahihi214;TrustServerCertificate=true"
    depends_on:
      - projectdb
    ports:
      - "8003:80"

