version: '3.4'

services:
  accountdb:
    container_name: accountdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://accountdb:27017"
    depends_on:
      - accountdb
    ports:
      - "8000:80"
